import asyncio
import sys
import argparse
import json
import uuid
import re
from pathlib import Path

# Add project root to sys.path
sys.path.insert(0, str(Path(__file__).parent))

from agents.orchestrator import Orchestrator
from agents.firewall import decide_request, execute_task

def print_separator(title=""):
    width = 80
    if title:
        padding = (width - len(title) - 2) // 2
        print(f"\n{'=' * padding} {title.upper()} {'=' * padding}\n")
    else:
        print(f"\n{'=' * width}\n")

async def main():
    parser = argparse.ArgumentParser(description="A.G.E.N.T.S Issue Logging CLI")
    parser.add_argument("issue", type=str, help="Description of the issue (e.g. 'Rain delay slab')")
    parser.add_argument("cost", type=str, nargs="?", default="0", help="Estimated cost impact")
    parser.add_argument("days", type=str, nargs="?", default="0", help="Estimated schedule impact in days")
    
    args = parser.parse_args()
    
    # Clean the inputs
    issue = args.issue
    cost = str(args.cost).replace('$', '').replace(',', '')
    days = str(args.days).replace('days', '').strip()
    
    user_input = f"Variation: +${cost}, +{days} days, {issue}"
    
    print_separator("A.G.E.N.T.S. CLI")
    print(f"INPUT STREAM: {user_input}")
    print_separator("AGENT REASONING STREAM")

    orchestrator = Orchestrator()
    request_id = None
    action_intent_payload = None

    # We will buffer the output to provide a clean summary at the end
    # but still show the stream live.
    
    try:
        async for chunk in orchestrator.astream_chat(user_input):
            if chunk.startswith("data: "):
                content = chunk.replace("data: ", "").strip()
                if content:
                    # Capture request ID if it signals proposal creation
                    match = re.search(r"Request ID: (APR-[A-Z0-9]+)", content)
                    if match:
                        request_id = match.group(1)
                    
                    # Print natively
                    print(content)
                    
    except KeyboardInterrupt:
        print("\n\n[SYSTEM] Stream interrupted by user.")
        sys.exit(1)
        
    print_separator("EXECUTION PREVIEW")
    
    if not request_id:
        print("[!] No approval request generated by the system. Interaction complete.")
        sys.exit(0)
        
    # Fetch the full request from firewall
    from agents.firewall import get_request
    request = get_request(request_id)
    if not request:
        print(f"[!] Critical Error: Request {request_id} not found in firewall registry.")
        sys.exit(1)
        
    intent = request.get("original_action_intent", {})
    metadata = intent.get("metadata", {})
    params = intent.get("parameters", {})
    
    print(f"DECISION:   {metadata.get('final_decision', 'UNKNOWN')}")
    print(f"CONFIDENCE: {params.get('confidence', 0.0)}")
    print(f"RISKS FLAG: {', '.join(params.get('risks', [])) or 'None'}")
    print("\nJUSTIFICATION:")
    print(metadata.get('final_justification', 'No justification provided.'))
    
    actions = params.get("actions", [])
    if actions:
        print(f"\nACTIONS ({len(actions)}):")
        for idx, act in enumerate(actions, 1):
            act_type = act.get("type", "unknown")
            print(f"  {idx}. [{act_type.upper()}] - {act.get('reason', '')}")
            
    print_separator()
    
    # The Prompt
    choice = input(f"Approve execution of {request_id}? (y/n): ").strip().lower()
    
    if choice in ['y', 'yes']:
        print(f"\n[GATEKEEPER] Approved. Routing to External Gateway...")
        try:
            decide_request(request_id, "approve", decided_by="cli_gatekeeper", reason="CLI Approval")
            
            # Note: We now execute the intent via the firewall which delegates securely to the gateway.
            result = await execute_task(request_id)
            
            print_separator("EXECUTION RESULT")
            print(json.dumps(result, indent=2))
            print_separator()
            
        except Exception as e:
            print(f"\n[ERROR] Execution failed: {e}")
            
    else:
        print(f"\n[GATEKEEPER] Rejected.")
        try:
            decide_request(request_id, "reject", decided_by="cli_gatekeeper", reason="CLI Rejection")
        except Exception as e:
            pass

if __name__ == "__main__":
    asyncio.run(main())
