"""
Phase 3A End-to-End Execution Demo
Goal: Demonstrates the full flow from Proposal -> Approval -> Gateway -> Gmail Side-effect.
"""

import os
import json
import sys
from pathlib import Path

# PRE-IMPORT ENV SETUP
import tempfile
os.environ["AGENTS_DB_PATH"] = tempfile.mktemp(suffix=".db")

# Add project root to path
sys.path.append(str(Path(__file__).parent.parent))

from agents.firewall import PreflightApprovalEngine
from agents.logic.external_gateway import ExternalGateway
from agents.logic import event_bus

def run_demo():
    print("=== A.G.E.N.T.S Phase 3A End-to-End Demo ===")
    
    gateway = ExternalGateway()
    approval_engine = PreflightApprovalEngine()
    
    # 1. THE INTENT (Generated by Aria in a real construction loop)
    trace_id = "trace-demo-123"
    action_intent = {
        "action": "gmail_draft",
        "agent_id": "jenny",
        "parameters": {
            "to": "boss@agencysite.com",
            "subject": "Status Report",
            "body": "Phase 3A Core Execution Layer is now active and verified."
        },
        "trace_id": trace_id,
        "requires_approval": True,
        "status": "pending",
        "summary": "Send status report to the boss."
    }
    
    print(f"\n[STEP 1] Creating Proposal Intent (Trace: {trace_id})")
    request = approval_engine.create_or_get_request(action_intent)
    approval_id = request["request_id"]
    print(f" -> Proposal created. Approval ID: {approval_id}")

    # 2. THE APPROVAL (Simulating Gatekeeper clicking 'Approve' in Cockpit)
    print(f"\n[STEP 2] Approving Proposal {approval_id}")
    approval_engine.decide_request(approval_id, "approve", reason="Demo approval manually triggered.")
    
    # Update local intent status for the gateway call (matches what the UI would do)
    action_intent["status"] = "approved"

    # 3. THE EXECUTION (Gateway Choke Point)
    print(f"\n[STEP 3] Handing off to External Gateway for Execution...")
    try:
        outcome = gateway.validate_and_execute(action_intent, approval_id)
        
        print("\n[SUCCESS] Execution Completed!")
        print(f" -> Execution Trace ID: {outcome['execution_trace_id']}")
        print(f" -> Result: {outcome['message']} (ID: {outcome['draft_id']})")
        
    except Exception as e:
        print(f"\n[FAILURE] Execution Blocked: {str(e)}")
        return

    print("\n[STEP 4] Verifying Audit Trail...")
    # In a real system, we'd check the events.log.jsonl
    # Here we just acknowledge that events were emitted during the execution.
    print(" -> EXECUTION_STARTED, EXTERNAL_SIDE_EFFECT_V1, and EXECUTION_COMPLETED logs generated.")

if __name__ == "__main__":
    run_demo()
